---
- name: install homebrew zsh
  homebrew: name=zsh state=latest update_homebrew=yes

- name: add zsh to /etc/shells
  lineinfile:
    line: /usr/local/bin/zsh
    dest: /etc/shells
    state: present
  register: zsh_enabled
  become: yes
  become_method: sudo

- name: set user shell to zsh
  command: chsh -s /usr/local/bin/zsh
  when: zsh_enabled.changed

